ARG BASE=node:20-alpine
FROM ${BASE} AS base

WORKDIR /app

# Instalar pnpm e wrangler
# RUN corepack enable pnpm && \
#    npm install -g wrangler

# RUN corepack enable pnpm && pnpm install
RUN apk add --no-cache git
RUN npm install -g corepack && corepack enable pnpm && pnpm install
RUN git config --global --add safe.directory /app
RUN pnpm install --force && pnpm add @cloudflare/workerd-linux-arm64
RUN chmod +x $(find /app/node_modules/.pnpm -name workerd)
RUN pnpm install -g wrangler

# Copiar arquivos de dependências
COPY package.json pnpm-lock.yaml ./

# Instalar dependências
RUN pnpm install

# Copiar código  fonte e scripts
COPY . .

# Garantir que o bindings.sh tem permissões de execução e formato correto
RUN tr -d '\r' < bindings.sh > bindings.tmp && \
    mv bindings.tmp bindings.sh && \
    chmod +x bindings.sh

# Build da aplicação
RUN pnpm run build

# Expor porta
EXPOSE 5173

# Configurar variáveis de ambiente
ENV NODE_ENV=production \
    RUNNING_IN_DOCKER=true

# Comando para iniciar usando o script dockerstart
CMD ["pnpm", "run", "dockerstart"]
